### ISSUE TITLE
stack-docker not finding verticle?

### ISSUE THREAD

**Issue by robertoestivill** [vert-x3/vertx-stack#23]
Hi,

I'm experiencing an issue with the example provided in the stack-docker readme. 
The issue is that for some reason the vertx-exec image is not able to locate the main verticle. 

```
$ docker run -i -t -p 8080:8080 \
     -v $PWD:/verticles vertx/vertx3-exec  \
     run com.example.MyVerticle \
     -cp /verticles/build/libs/api-0.1.1-fat.jar \

java.lang.ClassNotFoundException: com.example.MyVerticle
```

I have double check and the package and class name of the verticle is correct.
Moreover, the following command in my localhost works just fine

```
$ vertx run com.example.MyVerticle -cp build/libs/api-0.1.1-fat.jar

Succeeded in deploying verticle 
```

> Note: I build the fat jar to simplify the classpath argument and because i'm currently running the project with 
`java -jar api-0.1.1-fat.jar`

I'm quite new to Docker technologies, but as far I understand the above should be equivalent. 

Any ideas or tips on what might be going on? 
Is there any chance for this to be a bug in the docker image?
Thanks

**Comment by cescoffier** [comment]
As you are deploying a fat-jar you don't need this docker image. It would be much simpler with a "pure" java image (see https://github.com/vert-x3/vertx-examples/tree/master/docker-examples/vertx-docker-java-fatjar).

That's said, did you copy the your fat jar in side the /verticles location of your image ? Can you show me your `dockerFile` ?

**Comment by robertoestivill** [comment]
Thanks for link, I didn't know you guys had an example for fat jars.
Regarding copying the fatjar, I have not. I guess I thought vertx-exec was "ready" to run by passing the right parameters. 
Also, I assumed the fatjar would be available inside the container, as the directory is being mounted as volume. 

As I mentioned before, I'm quite new to docker, so excuse me if this are assumptions or questions outside the Vertx scope.

Thanks again
Robert

**Comment by cescoffier** [comment]
Can you show me the docker run command you used ? If the directory is mounted as a volume it should have worked.

**Comment by robertoestivill** [comment]
Here is the command.  I added a `tree` of the build directory just so we discard being in an incorrect directory.

```
$ tree build/libs/
build/libs/
└── api-0.1.1-fat.jar

0 directories, 1 file

$ docker run -i -t -p 8080:8080 -v $PWD:/mount vertx/vertx3-exec run com.example.MyVerticle -cp /mount/build/libs/api-0.1.1-fat.jar
java.lang.ClassNotFoundException: com.example.MyVerticle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:42)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$119(DeploymentManager.java:159)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:537)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:337)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:221)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:211)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:309)
	at io.vertx.core.Launcher.main(Launcher.java:48)
Failed in deploying verticle 
java.lang.ClassNotFoundException: com.example.MyVerticle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:42)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$119(DeploymentManager.java:159)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:537)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:337)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:221)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:211)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:309)
	at io.vertx.core.Launcher.main(Launcher.java:48)

java.lang.ClassNotFoundException: com.example.MyVerticle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:42)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$119(DeploymentManager.java:159)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:537)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:337)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:221)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:211)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:346)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:309)
	at io.vertx.core.Launcher.main(Launcher.java:48)
```

**Comment by cescoffier** [comment]
I will try it. Because if mounted correctly it should find it.

**Comment by cescoffier** [comment]
This works for me:

```
docker run -i -t -p 8080:8080 -v $PWD:/application vertx/vertx3-exec run io.vertx.devoxx.data.impl.DataStorageVerticle -cp /application/target/data-storage-service-1.0-SNAPSHOT-fat.jar
```

**Comment by robertoestivill** [comment]
I tried with different directories and still not working for me. Sounds like it might be a problem with the volume mount and my local installation (osx). Haven't read in detail yet, but looks like i'm stuck on this issue https://github.com/docker/docker/issues/4023

**Comment by cescoffier** [comment]
Docker issue. Closing.

**Comment by auryn31** [comment]
I have the same error, but with building the fat jar in the container o.O
