### ISSUE TITLE
Convergence issue with Scala SDK

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-stack#56]
CI fails with:

```
testConvergence(io.vertx.stack.VertxStacksTest)  Time elapsed: 17.841 sec  <<< ERROR!
io.vertx.stack.model.DependencyConflictException: Conflict detected for artifact org.scala-lang:scala-library:jar - version 2.11.8 was already selected while io.vertx:vertx-mysql-postgresql-client:jar:3.4.0-SNAPSHOT depends on version 2.11.7
	at io.vertx.stack.model.StackResolution.lambda$resolve$8(StackResolution.java:167)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at io.vertx.stack.model.StackResolution.resolve(StackResolution.java:158)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.vertx.stack.model.StackResolution.resolve(StackResolution.java:75)
	at io.vertx.stack.VertxStacksTest.testConvergence(VertxStacksTest.java:117)
```

**Comment by vietj** [comment]
is it because of vertx-codetrans ?

**Comment by vietj** [comment]
because scala has not been added to stack, only codetrans afair

**Comment by cescoffier** [comment]
Let me check.

This test (very long) checks that we always converge to the same version in all our dependencies. It's more a warning like: "Hey, something has changed, please align the versions".

**Comment by cescoffier** [comment]
Ok, after some investigations here is what I've captured:

```
WARNING: Conflict detected for artifact org.scala-lang:scala-library:jar - version 2.11.8 was already selected by [io.vertx:vertx-http-service-factory:jar:3.4.0-SNAPSHOT, io.vertx:vertx-rx-groovy:jar:3.4.0-SNAPSHOT, io.vertx:vertx-rx-js:jar:3.4.0-SNAPSHOT, io.vertx:vertx-auth-jdbc:jar:3.4.0-SNAPSHOT, io.vertx:vertx-sockjs-service-proxy:jar:3.4.0-SNAPSHOT] while io.vertx:vertx-mysql-postgresql-client:jar:3.4.0-SNAPSHOT depends on version 2.11.7
```

(I've added the list of artifacts depending to the artifact, I guess it could be nice for debugging).

If I look at vertx-http-service-factory, it requires:
```
io.vertx:vertx-http-service-factory:jar:3.4.0-20161025.114315-215, 
io.vertx:vertx-core:jar:3.4.0-20161025.113754-212,
 io.netty:netty-common:jar:4.1.5.Final, 
io.netty:netty-buffer:jar:4.1.5.Final, 
io.netty:netty-transport:jar:4.1.5.Final, 
io.netty:netty-handler:jar:4.1.5.Final,
 io.netty:netty-codec:jar:4.1.5.Final, 
io.netty:netty-handler-proxy:jar:4.1.5.Final, 
io.netty:netty-codec-socks:jar:4.1.5.Final,
 io.netty:netty-codec-http:jar:4.1.5.Final,
 io.netty:netty-codec-http2:jar:4.1.5.Final, 
io.netty:netty-resolver:jar:4.1.5.Final, 
io.netty:netty-resolver-dns:jar:4.1.5.Final,
 io.netty:netty-codec-dns:jar:4.1.5.Final,
 com.fasterxml.jackson.core:jackson-core:jar:2.7.4,
com.fasterxml.jackson.core:jackson-databind:jar:2.7.4, 
com.fasterxml.jackson.core:jackson-annotations:jar:2.7.0,
 io.vertx:vertx-codegen:jar:3.4.0-20161022.154241-13,
 org.mvel:mvel2:jar:2.2.8.Final, 
io.vertx:vertx-service-factory:jar:3.4.0-20161025.114856-213, 
**io.vertx:vertx-codetrans:jar:3.4.0-20161025.114654-221, 
io.vertx:vertx-lang-scala-on-the-fly_2.11:jar:3.4.0-20161025.000340-4, 
org.scala-lang:scala-library:jar:2.11.8,
 org.scala-lang:scala-compiler:jar:2.11.8, 
org.scala-lang:scala-reflect:jar:2.11.8, 
org.scala-lang.modules:scala-xml_2.11:jar:1.0.4,
 org.scala-lang.modules:scala-parser-combinators_2.11:jar:1.0.4,**
org.bouncycastle:bcpg-jdk15on:jar:1.54, org.bouncycastle:bcprov-jdk15on:jar:1.54
```

So codetrans depends on scala. Does it have to be a `compile` (scope) dependency ? Should I detect codetrans and ignore it (cut the graph) ? I don't think we should embed scala dependencies if not explicitly required. WDYT ?

**Comment by cescoffier** [comment]
I've opened another issue to improve the reporting (#57)

**Comment by vietj** [comment]
we should have an optional / compile / provided dependency indeed

**Comment by vietj** [comment]
just made it optional=true like the other

**Comment by cescoffier** [comment]
ok, so once they have been built, it should be back on track.

**Comment by cescoffier** [comment]
I'm not a scala expert, but I believe we should update the scala version of the async mysql / postgres driver ?

**Comment by tsegismont** [comment]
I haven't checked, just created the issues after looking at vertx3-ci
mailing list. Codetrans is probably the cause, since there were some
updates in this area recently.

2016-10-25 13:27 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by cescoffier** [comment]
Issue fixed in codetrans.
